#!/usr/bin/env bash
# World wide web
search_subdomain () {
	local domain="$1"
	local subdomain="$2"
	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains=("$subdomain")
	fi
	for sub in "${subdomains[@]}"; do
		type_of_record=$(dig "$sub.$domain" | awk "/ANSWER SECTION/ { getline; print \$4 }")
		destination=$(dig +short "$sub.$domain")
		echo "The subdomain $sub is a $type_of_record record and points to $destination"
	done
	}
search_subdomain "$1" "$2"
