#!/usr/bin/env bash
# This script allow us to nstall nginx web server
apt-get -y install nginx
sudo service nginx start
echo 'Hello World!' | sudo tee /var/www/html/index.html
#sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
