#!/usr/bin/env bash
# This script allow us to nstall nginx web server
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' | tee /var/www/html/index.html
#sed -i 's#root /var/www/html;#root /var/www/html;#g' /etc/nginx/sites-available/default
service nginx restart
