#!/usr/bin/env bash
# This script the Nginx server so that /redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
sh -c 'echo "Hello World!" | tee /var/www/html/index.html'
sh -c 'echo "server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.html;
    }
    location /redirect_me {
        rewrite ^/testone(.*)http://www.google.com permanent;
    }
}" >> /etc/nginx/sites-available/default'
service nginx restart
