#!/usr/bin/env bash
# Configuration of a Header response.
sudo apt-get update
sudo apt-get install -y nginx
HOSTNAME=$(hostname)
sh -c "echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    location / {
    add_header X-Served-By '\"'$HOSTNAME'\"';
    }
}' | tee /etc/nginx/sites-available/default"
sudo service nginx restart
