#!/usr/bin/env bash
# Installation of load balancer
sudo apt-get update
sudo apt-get install haproxy -y

CONFIG="frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 433189-web-01 100.25.200.71:80 check
    server 433189-web-02 54.160.97.207:80 check"

echo "$CONFIG" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
