#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive out of it.
if [ "$#" -ne 1 ]; then
	echo "Usage: "$0" <password>"
	exit 1
fi
DATE=$(date +%d-%m-%Y)
mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czf $DATE.tar.gz backup.sql
