#!/usr/bin/env bash
# Debugging_1

sudo apt-get update
sudo apt-get install nginx -y
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
