#!/usr/bin/env bash
# that script displays To infinity and beyond indefinitely.
hand_sigterm() {
    echo "I am invincible!!!"
}
trap "hand_sigterm" SIGTERM
i=1
while [ "$i" -eq 1 ]
do
    echo "To infinity and beyond"
    sleep 2
done
