#!/usr/bin/env bash
#That script  displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
i=0
j=8
while ((i < 10))
do
    if [ $i  -eq $j ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$((i + 1))
done
