#!/usr/bin/env bash
#That script loops from 1 to 10

for ((i = 1; i <= 10; i++));
do
    if [ "$i" -eq 4 ];
    then
	echo "bad luck"
    elif [ "$i" -eq 8 ];
    then
	echo "good luck"
    else
	echo "Best School"
    fi
done
