#!/usr/bin/env bash
#displays The content of the current directory In a list format.
for file in [!_.]*
do
    if [ -f "$file" ]
    then
	new_name=$(echo "$file" | cut -d'-' -f2-)
	echo "$new_name"
    fi
done
