#!/usr/bin/env bash
#That script gives information about the school file.
file="school"
if [ -f "$file" ]
then
    echo "school file exists"
    if [ ! -s "$file" ]
    then
        echo "school file is empty"
    else
	echo "school file is not empty"
    fi
    echo "school is a regular file"
else
    echo "school file does not exist"
fi
