#!/usr/bin/env bash
#That script gives information about the school file.
file="school"
if [ -f "$file" ]
then
    echo "school file exists"
    if [ ! -s "$file" ]
    then
        echo "school file is empty"
    fi
    if [ -s "$file" ]
    then
        echo "school file is not empty"
    fi
    if [ -f "$file" ]
    then
        echo "school is a regular file"
    fi
    if [ ! -f "$file" ]
    then
	: # This is a no-operation command
    fi
else
    echo "school file does not exist"
fi
