#!/usr/bin/env bash
#That script configures an Ubuntu server
sudo cp /etc/hosts ~/hosts.new
sed -i '$a\8.8.8.8       facebook.com' ~/hosts.new
sed -i 's/^127\.0\.0\.1/127.0.0.2/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
